version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: auraflow
      POSTGRES_USER: auraflow
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auraflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  auraflow:
    build: .
    ports:
      - "8080:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REACT_APP_API_URL=http://localhost:8080
      - DEBUG=*
      - DATABASE_URL=postgresql://auraflow:password@postgres:5432/auraflow?sslmode=disable
      - DOCKER_ENV=true
      - LLM_BASE_URL=https://api.groq.com/openai/v1
      - LLM_API_KEY=${LLM_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
